package top.jimmyweb.concurrency02.dao;

import top.jimmyweb.concurrency02.dataobject.MiaoshaGoods;

public interface MiaoshaGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_goods
     *
     * @mbg.generated Sat Jul 20 15:28:31 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_goods
     *
     * @mbg.generated Sat Jul 20 15:28:31 CST 2019
     */
    int insert(MiaoshaGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_goods
     *
     * @mbg.generated Sat Jul 20 15:28:31 CST 2019
     */
    int insertSelective(MiaoshaGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_goods
     *
     * @mbg.generated Sat Jul 20 15:28:31 CST 2019
     */
    MiaoshaGoods selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_goods
     *
     * @mbg.generated Sat Jul 20 15:28:31 CST 2019
     */
    int updateByPrimaryKeySelective(MiaoshaGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_goods
     *
     * @mbg.generated Sat Jul 20 15:28:31 CST 2019
     */
    int updateByPrimaryKey(MiaoshaGoods record);


    /**
     * stock_count>0的时候才去更新，数据库本身会有锁，那么就不会在数据库中同时多个线程更新一条记录，使用数据库特性来保证超卖的问题
     * @param goodsId
     */
    public void reduceStock(long goodsId);
}